# Very simple makefile for compiling calculate_sed_inner_loop.c

all: calculate_sed_inner_loop

calculate_sed_inner_loop: calculate_sed_inner_loop.c
	gcc -std=c99 -O2 calculate_sed_inner_loop.c -o calculate_sed_inner_loop

clean:
	rm calculate_sed_inner_loop