%%
% Runs a chi^2 test to compare whether the counts in s0 (the expected
% counts) and those in s1 (the test counts) were generated by the same
% distribution.  Unlike compare_categories.m, this m-file groups the
% s0 counts and s1 counts by the name field.  So all bins with the same
% name are binned together into a single bin before the chi^2 test is
% applied.
%
% s0_counts_file: Counts of expected elements in each category 
% s1_counts_file: Counts of observed elements in each category
% sed_file: File of String-edit distances between caegories (NOT USED)
% output_file: File to which the result of the hyp. test should be written
% s0_cdf_file File to which CDF of category counts from s0 should sent
% s1_cdf_file: File to which CDF of category counts from s1 should be sent
%%
function [] = compare_high_level_type_counts(s0_counts_file, s1_counts_file, sed_file, output_file, stats_file, s0_cdf_file, s1_cdf_file)

if nargin ~= 7,
    error('Invalid number of arguments');
end

[s0_ids, s0_counts, names] = textread(s0_counts_file, '%d %d %s');
[s1_ids, s1_counts, names] = textread(s1_counts_file, '%d %d %s');

% Create a list of indices ot iterate over
idxs = 1:size(names, 1);
merged_bin_idx = 0;

% Iterate over the indices merging common elements
while(~isempty(idxs)),
    current_idx = idxs(1),
     merged_bin_idx = merged_bin_idx + 1;
       
    identical_idxs = find(strcmp(names(current_idx), names) == 1),
    
    s0_merged_counts(merged_bin_idx, 1) = 0;
    s1_merged_counts(merged_bin_idx, 1) = 0;
    merged_names(merged_bin_idx, 1) = names(current_idx, 1);
    
    for i = [identical_idxs]',
        s0_merged_counts(merged_bin_idx, 1) = s0_merged_counts(merged_bin_idx, 1) + s0_counts(i, 1);
        s1_merged_counts(merged_bin_idx, 1) = s1_merged_counts(merged_bin_idx, 1) + s1_counts(i, 1);
    end
    
    idxs = setdiff(idxs, identical_idxs);
 end

%%
% Run the hypothesis test
    chi_squared_stat = sum( (s1_merged_counts - s0_merged_counts).^2./(s0_merged_counts));
    p = 1 - chi2cdf(chi_squared_stat, size(s0_merged_counts, 1) - 1);
    h = 0;
    if (p < 0.05) 
        h = 1,
    end
        
    
    
    
    